version: "3"
services:
  bitcoind:
    restart: unless-stopped
    container_name: btcpayserver_bitcoind
    image: btcpayserver/bitcoin:0.21.1
    environment:
      BITCOIN_NETWORK: ${NETWORK:-mainnet}
      BITCOIN_WALLETDIR: "/walletdata"
      BITCOIN_EXTRA_ARGS: |
        rpcport=43782
        rpcbind=0.0.0.0:43782
        rpcallowip=0.0.0.0/0
        port=39388
        whitelist=0.0.0.0/0
        maxmempool=500
        prune=50000
        ${RPC_AUTH:- }
      VIRTUAL_PORT: 43782
      VIRTUAL_HOST: ${BITCOIN_HOST}
      VIRTUAL_HOST_NAME: "bitcoind"
      SSL_POLICY: Mozilla-Modern
      LETSENCRYPT_HOST: ${BITCOIN_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL:-<no value>}
    expose:
    - "43782"
    - "39388"
    ports:
    - "8333:39388"
    volumes:
    - "bitcoin_datadir:/data"
    - "bitcoin_wallet_datadir:/walletdata"
  letsencrypt-nginx-proxy-companion:
    restart: unless-stopped
    image: btcpayserver/letsencrypt-nginx-proxy-companion:1.12.2
    container_name: letsencrypt-nginx-proxy-companion
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:ro"
    - "nginx_conf:/etc/nginx/conf.d"
    - "nginx_vhost:/etc/nginx/vhost.d"
    - "nginx_html:/usr/share/nginx/html"
    - "nginx_certs:/etc/nginx/certs:rw"
    environment:
      NGINX_DOCKER_GEN_CONTAINER: "nginx-gen"
      NGINX_PROXY_CONTAINER: "nginx"
      ACME_CA_URI: ${ACME_CA_URI:-production}
    links:
    - nginx-gen
  nginx-gen:
    restart: unless-stopped
    image: btcpayserver/docker-gen:0.7.8
    container_name: nginx-gen
    environment:
      DEFAULT_HOST: ${BITCOIN_HOST}
    volumes:
    - "/var/run/docker.sock:/tmp/docker.sock:ro"
    - "./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
    - "nginx_conf:/etc/nginx/conf.d"
    - "nginx_vhost:/etc/nginx/vhost.d"
    - "nginx_html:/usr/share/nginx/html"
    - "nginx_certs:/etc/nginx/certs:ro"
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    links:
    - nginx
  nginx:
    restart: unless-stopped
    image: nginx:1.16.0
    container_name: nginx
    ports:
    - "${REVERSEPROXY_HTTP_PORT:-80}:80"
    - "${REVERSEPROXY_HTTPS_PORT:-443}:443"
    volumes:
    - "nginx_conf:/etc/nginx/conf.d"
    - "nginx_vhost:/etc/nginx/vhost.d"
    - "nginx_html:/usr/share/nginx/html"
    - "nginx_certs:/etc/nginx/certs:ro"
volumes:
  nginx_conf:
  nginx_vhost:
  nginx_html:
  nginx_certs:
  bitcoin_datadir:
  bitcoin_wallet_datadir: